version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - nilerr
    - errorlint

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - unnamedResult
        - paramTypeCombine

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
